// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlyEfGUepAp2VVui7tDGVoQhH7qPXSuCo',
    appId: '1:285240096489:web:bff944efe47188ac93e278',
    messagingSenderId: '285240096489',
    projectId: 'factory-solution-d822f',
    authDomain: 'factory-solution-d822f.firebaseapp.com',
    storageBucket: 'factory-solution-d822f.firebasestorage.app',
    databaseURL: "https://factory-solution-d822f-default-rtdb.asia-southeast1.firebasedatabase.app",
    measurementId: 'G-CN3X52QESB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvy9LMSuheSwWpgI-fFVeJuXRNPyNZwY8',
    appId: '1:285240096489:android:403473311763995793e278',
    messagingSenderId: '285240096489',
    projectId: 'factory-solution-d822f',
    databaseURL: "https://factory-solution-d822f-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'factory-solution-d822f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQkY7EdtzqLGIju0o11BK4kpm0TgnB2co',
    appId: '1:285240096489:ios:b61c1aa4411dcf8993e278',
    messagingSenderId: '285240096489',
    projectId: 'factory-solution-d822f',
    storageBucket: 'factory-solution-d822f.firebasestorage.app',
    databaseURL: "https://factory-solution-d822f-default-rtdb.asia-southeast1.firebasedatabase.app",
    iosBundleId: 'com.example.factorySolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQkY7EdtzqLGIju0o11BK4kpm0TgnB2co',
    appId: '1:285240096489:ios:b61c1aa4411dcf8993e278',
    messagingSenderId: '285240096489',
    projectId: 'factory-solution-d822f',
    storageBucket: 'factory-solution-d822f.firebasestorage.app',
    databaseURL: "https://factory-solution-d822f-default-rtdb.asia-southeast1.firebasedatabase.app",
    iosBundleId: 'com.example.factorySolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlyEfGUepAp2VVui7tDGVoQhH7qPXSuCo',
    appId: '1:285240096489:web:f03bae04301b137b93e278',
    messagingSenderId: '285240096489',
    projectId: 'factory-solution-d822f',
    authDomain: 'factory-solution-d822f.firebaseapp.com',
    storageBucket: 'factory-solution-d822f.firebasestorage.app',
    databaseURL: "https://factory-solution-d822f-default-rtdb.asia-southeast1.firebasedatabase.app",
    measurementId: 'G-0SM7NKPWDY',
  );
}
